
const proSettings = {
  // navTheme: 'light',
  // primaryColor: '#1890ff',
  // layout: 'side',
  // contentWidth: 'Fluid',
  // fixedHeader: true,
  // fixSiderbar: true,
  // pwa: false,
  // headerHeight: 48,
  // siderWidth: 200,
  // "colorPrimary": "#1890ff",
  // splitMenus: false,
  // colorWeak: false,
  // isTabs: false,

  "navTheme": "light",
  "layout": "side",
  "contentWidth": "Fluid",
  "fixedHeader": true,
  "fixSiderbar": true,
  "pwa": false,
  "headerHeight": 40,
  "siderWidth": 200,
  "isTabs": true,
  "colorPrimary": "#FA541C",
  "splitMenus": false,

  // "navTheme": "realDark",
  // "layout": "side",
  // "contentWidth": "Fluid",
  // "fixedHeader": true,
  // "fixSiderbar": true,
  // "pwa": false,
  // "headerHeight": 40,
  // "siderWidth": 200,
  // "isTabs": true,
  // "colorPrimary": "#F5222D",
  // "splitMenus": false,
  // "theme": "summerTheme"
};
export default proSettings;
